spring:
  application:
    name: hyoji-service
  profiles:
    active: local
  jwt:
    secret: goodFinger!@#

logging:
  level:
    root: info
    com.backend.goodfinger: debug

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

# local
---
server:
  port: 8081
spring:
  profiles: local
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: goodFinger
      username: hyo
      password: hyo

# localServer
---
server:
  port: 80
spring:
  profiles: localServer
  data:
    mongodb:
      host: mongo
      port: 27017
      database: goodFinger
      username: hyo
      password: hyo

# server
---
server:
  port: 8080
spring:
  profiles: server
  data:
    mongodb:
      host: mongo
      port: 27017
      database: goodFinger
      username: hyo
      password: hyo