spring:
  profiles:
    active: local

# local
---

logging:
  config: classpath:log4j2.yml

---
server:
  port: 8082
spring:
  profiles: local
  data:
    mongodb:
      host: goodfinger.com
      port: 27017
      database: goodFinger
      username: dphong
      password: 1234
file:
  uploadDir = /d/test/

# localServer
---
server:
  port: 80
spring:
  profiles: localServer
  data:
    mongodb:
      host: mongo
      port: 27017
      database: admin
      username: dphong
      password: 1234

# server
---
server:
  port: 8080
spring:
  profiles: server
  data:
    mongodb:
      host: mongo
      port: 27017
      database: goodFinger
      username: dphong
      password: 1234
